# Generated by Django 2.0.7 on 2018-07-12 09:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(blank=True, max_length=280)),
                ('faq_answer', wagtail.core.fields.RichTextField(blank=True)),
                ('data_target', models.CharField(blank=True, max_length=280)),
                ('aria_controls', models.CharField(blank=True, max_length=280)),
                ('aria_labelledby', models.CharField(blank=True, max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('faq_title', models.CharField(blank=True, max_length=100)),
                ('faq_subTitle', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
