# Generated by Django 2.0.7 on 2018-07-05 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('faqTitle', models.CharField(blank=True, max_length=100)),
                ('faqSubTitle', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='faq',
            name='faqSubTitle',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='faqTitle',
        ),
    ]
