# Generated by Django 2.0.7 on 2018-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20180705_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='ariaControls',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='faq',
            name='ariaLabelledby',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='faq',
            name='dataTarget',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
