# Generated by Django 2.0.7 on 2018-07-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_auto_20180705_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='ariaControls',
            new_name='aria_controls',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='ariaLabelledby',
            new_name='aria_labelledby',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='dataTarget',
            new_name='data_target',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='faqAnswer',
            new_name='faq_answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='faqQuestion',
            new_name='faq_question',
        ),
        migrations.RenameField(
            model_name='faqpage',
            old_name='faqSubTitle',
            new_name='faq_subTitle',
        ),
        migrations.RenameField(
            model_name='faqpage',
            old_name='faqTitle',
            new_name='faq_title',
        ),
    ]
