version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: omahelsinki
      POSTGRES_PASSWORD: omahelsinki
      POSTGRES_DB: omahelsinki
    ports:
      - "5434:5432"
    volumes:
      - omahelsinki-postgres-data-volume:/var/lib/postgres/data
    container_name: omahelsinki-db

  django:
    build:
      context: .
      target: development
    env_file:
      - docker-compose.env.yaml
    environment:
      DATABASE_URL: postgres://omahelsinki:omahelsinki@omahelsinki-db/omahelsinki
      DATABASE_HOST: omahelsinki-db
    volumes:
      - .:/app
      - omahelsinki-media-volume:/var/media/
      - /app/node_modules
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    container_name: omahelsinki

  react:
    build:
      context: .
      target: development
    environment:
      SERVER_URL: 0.0.0.0
      SKIP_DATABASE_CHECK: 1
    container_name: omahelsinki-react
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: yarn start

volumes:
  ? omahelsinki-postgres-data-volume
  ? omahelsinki-media-volume


networks:
  default:
    name: helsinki
