# Generated by Django 2.0.7 on 2018-07-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='heroBody',
            new_name='hero_body',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='heroHeading',
            new_name='hero_heading',
        ),
    ]
